import jsPDF from "jspdf";

export const generatePdf = (proposal) => {
  const doc = new jsPDF();

  // ---------------------------
  // Header
  // ---------------------------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("CLIENT PROPOSAL", 105, 20, { align: "center" });

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Generated by Client Proposal Builder", 105, 28, {
    align: "center",
  });

  doc.line(20, 35, 190, 35);

  // ---------------------------
  // Prepared For
  // ---------------------------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Prepared For", 20, 48);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  doc.text(`Client Name : ${proposal.clientName}`, 20, 58);
  doc.text(`Client Email : ${proposal.clientEmail}`, 20, 66);

  doc.line(20, 74, 190, 74);

  // ---------------------------
  // Project Details
  // ---------------------------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Project Details", 20, 86);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  doc.text(`Project Title : ${proposal.title}`, 20, 96);
  doc.text(`Timeline : ${proposal.timeline}`, 20, 104);
  doc.text(`Budget : ₹${proposal.price}`, 20, 112);
  doc.text(`Status : ${proposal.status}`, 20, 120);

  doc.line(20, 128, 190, 128);

  // ---------------------------
  // Description
  // ---------------------------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Project Description", 20, 140);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  const description = doc.splitTextToSize(
    proposal.projectDescription,
    170
  );

  doc.text(description, 20, 150);

  // Find where the description ends
  const descriptionEndY = 150 + description.length * 7;

  doc.line(20, descriptionEndY + 5, 190, descriptionEndY + 5);

  // ---------------------------
  // Terms & Conditions
  // ---------------------------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Terms & Conditions", 20, descriptionEndY + 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  doc.text("• 50% advance payment before work begins.", 25, descriptionEndY + 30);
  doc.text("• Remaining payment after project completion.", 25, descriptionEndY + 38);
  doc.text("• Proposal is valid for 30 days.", 25, descriptionEndY + 46);

  // ---------------------------
  // Signature
  // ---------------------------
  doc.line(20, 255, 80, 255);
  doc.text("Authorized Signature", 20, 262);

  // ---------------------------
  // Footer
  // ---------------------------
  doc.setFontSize(11);
  doc.text("Thank you for your business!", 105, 280, {
    align: "center",
  });

  doc.save(`${proposal.title}.pdf`);
};